-- MySQL Script generated by MySQL Workbench
-- Mon Nov 23 10:14:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema MariosPizzaBar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `MariosPizzaBar` ;

-- -----------------------------------------------------
-- Schema MariosPizzaBar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `MariosPizzaBar` DEFAULT CHARACTER SET utf8 ;
USE `MariosPizzaBar` ;

-- -----------------------------------------------------
-- Table `MariosPizzaBar`.`OrderList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MariosPizzaBar`.`OrderList` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MariosPizzaBar`.`PizzaIngredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MariosPizzaBar`.`PizzaIngredients` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Ingredients` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `MariosPizzaBar`.`PizzaList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `MariosPizzaBar`.`PizzaList` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  `Price` FLOAT NOT NULL,
  `OrderList_ID` INT NOT NULL,
  `PizzaIngredients_ID` INT NOT NULL,
  PRIMARY KEY (`ID`, `OrderList_ID`, `PizzaIngredients_ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC) VISIBLE,
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE,
  INDEX `fk_PizzaList_OrderList_idx` (`OrderList_ID` ASC) VISIBLE,
  INDEX `fk_PizzaList_PizzaIngredients1_idx` (`PizzaIngredients_ID` ASC) VISIBLE,
  CONSTRAINT `fk_PizzaList_OrderList`
    FOREIGN KEY (`OrderList_ID`)
    REFERENCES `MariosPizzaBar`.`OrderList` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PizzaList_PizzaIngredients1`
    FOREIGN KEY (`PizzaIngredients_ID`)
    REFERENCES `MariosPizzaBar`.`PizzaIngredients` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
